// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "1957a277-5a1b-49be-89a7-85e73ebc0702";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password


float apparentPOW;
float irms;
float powerFactor;
float realPOW;
float voltRMS;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(apparentPOW, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(irms, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(powerFactor, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(realPOW, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(voltRMS, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
